[workspace]
authors = ["Youssef-Harby <me@youssefharby.com>"]
channels = ["conda-forge"]
name = "flac-raster"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.1"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
rasterio = ">=1.4.3,<2"
numpy = ">=2.3.1,<3"
typer = ">=0.16.0,<0.17"
rich = ">=14.0.0,<15"
tqdm = ">=4.67.1,<5"
pytest = ">=8.4.1,<9"
pytest-cov = ">=6.2.1,<7"
mutagen = ">=1.47.0,<2"

[pypi-dependencies]
pyflac = ">=3.0.0, <4"
requests = ">=2.32.4, <3"
